spring.application.name=reception-service
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]
server.port=${RECEPTION_SERVER_PORT:8081}
billing.service.url=http://localhost:8082
spring.data.mongodb.uri=${RECEPTION_MONGO_URI:mongodb://localhost:27017/medical_reception}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
