spring.application.name=reception-service
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]
server.port=${RECEPTION_SERVER_PORT:8081}
spring.data.mongodb.uri=${RECEPTION_MONGO_URI:mongodb://localhost:27017/medical_reception}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
