apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-config
  namespace: medical-center
  labels:
    app: billing-service
data:
  SERVER_PORT: "8082"
  BILLING_SERVER_PORT: "8082"
  BILLING_DB_NAME: "medical_billing"
  BILLING_MONGO_URI: "mongodb://billing-db:27017/medical_billing"
  SPRING_DATA_MONGODB_URI: "mongodb://billing-db:27017/medical_billing"
  SPRING_MONGODB_URI: "mongodb://billing-db:27017/medical_billing"
  BILLING_SERVICE_URL: "http://billing-service:8082"
