apiVersion: v1
kind: Service
metadata:
  name: medical-records-service
  namespace: medical-center
  labels:
    app: medical-records-service
spec:
  type: ClusterIP
  selector:
    app: medical-records-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
