apiVersion: v1
kind: Service
metadata:
  name: reception-service
  namespace: medical-center
  labels:
    app: reception-service
spec:
  type: ClusterIP
  selector:
    app: reception-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081