apiVersion: v1
kind: ConfigMap
metadata:
  name: reception-config
  namespace: medical-center
  labels:
    app: reception-service
data:
  SERVER_PORT: "8081"
  RECEPTION_SERVER_PORT: "8081"
  RECEPTION_DB_NAME: "medical_reception"
  RECEPTION_MONGO_URI: "mongodb://reception-db:27017/medical_reception"
  SPRING_DATA_MONGODB_URI: "mongodb://reception-db:27017/medical_reception"
  SPRING_MONGODB_URI: "mongodb://reception-db:27017/medical_reception"
  RECEPTION_SERVICE_URL: "http://reception-service:8081"
