apiVersion: v1
kind: Secret
metadata:
  name: medical-secrets
  namespace: medical-center
  labels:
    app.kubernetes.io/part-of: medical-system
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: "root_username_secret"
  MONGO_ROOT_PASSWORD: "root_password_secret"
  RECEPTION_DB_USER: "reception_admin_secret"
  RECEPTION_DB_PASSWORD: "reception_password_secret"
  BILLING_DB_USER: "billing_admin_secret"
  BILLING_DB_PASSWORD: "billing_password_secret"
  MEDICAL_RECORDS_DB_USER: "medical_records_admin_secret"
  MEDICAL_RECORDS_DB_PASSWORD: "medical_records_password_secret"
  NOTIFICATION_DB_USER: "notification_admin_secret"
  NOTIFICATION_DB_PASSWORD: "notification_password_secret"
