spring.application.name=billing-service
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]
server.port=${BILLING_SERVER_PORT:8082}
spring.data.mongodb.uri=${BILLING_MONGO_URI:mongodb://localhost:27017/medical_billing}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
